# Generated by Django 2.2.4 on 2019-08-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='definition',
            field=models.TextField(),
        ),
    ]
