# Generated by Django 2.2.4 on 2019-08-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0002_auto_20190829_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ('transliteration', 'word')},
        ),
        migrations.AddField(
            model_name='keyword',
            name='transliteration',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
