# Generated by Django 2.2.4 on 2019-08-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0004_auto_20190829_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='keyWords',
        ),
        migrations.AddField(
            model_name='post',
            name='keyWords',
            field=models.ManyToManyField(related_name='words', to='commentaries.KeyWord'),
        ),
    ]
