# Generated by Django 2.2.5 on 2019-09-03 01:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commentaries', '0005_auto_20190830_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Thought',
        ),
    ]

    atomic = False
