# Generated by Django 2.2.5 on 2019-09-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0006_auto_20190902_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='keyWords',
            field=models.ManyToManyField(blank=True, related_name='words', to='commentaries.KeyWord'),
        ),
    ]
